server:
  port: 10010
spring:
  cloud:
    nacos:
      server-addr: localhost:8848 #nacos地址
    gateway:
      routes:
        - id: goods-service #唯一标志
          uri: lb://goods #lb(负载平衡)+注册的服务的名称  或是   http://+地址:端口
          predicates:
            - Path=/goods/** #判断是否以goods开头
        - id: user-service #唯一标志
          uri: lb://user #lb(负载平衡)+注册的服务的名称  或是   http://+地址:端口
          predicates:
            - Path=/user/** #判断是否以user开头
        - id: order-service #唯一标志
          uri: lb://order #lb(负载平衡)+注册的服务的名称  或是   http://+地址:端口
          predicates:
            - Path=/order/** #判断是否以order开头
  main:
    web-application-type: reactive
  application:
    name: gateway

